idle_bg = "#151515"
idle_fg = "#dcd7ba"
info_bg = "#2d4f67"
info_fg = "#dcd7ba"
good_bg = "#151515"
good_fg = "#98971a"
warning_bg = "#ff9e3b"
warning_fg = "#16161D"
critical_bg = "#e82424"
critical_fg = "#dcd7ba"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#151515"
