theme = "kanagawa"

[editor]
line-number = "absolute"
auto-completion = true
auto-format = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "file-encoding", "file-type", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "error"
