[general]
live_config_reload = false
import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]

[font]
size = 14

[font.bold]
family = "Jetbrains Mono NF"
style = "Bold"

[font.bold_italic]
family = "Jetbrains Mono NF"
style = "Bold Italic"

[font.italic]
family = "Jetbrains Mono NF"
style = "Italic"

[font.normal]
family = "Jetbrains Mono NF"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[window]
opacity = 1.0

[window.padding]
x = 4
y = 4
