[theme]
theme = "kanagawa"
[theme.overrides]
separator = "<span size='17000'></span>"

[icons]
icons = "material-nf"
[icons.overrides]
sleep = "󰒲"
no_sleep = "󰒳"

[[block]]
block = "toggle"
format = " $icon  "
command_state = "pgrep swayidle"
command_on = "swaymsg 'exec swayidle -w'"
command_off = "pkill swayidle"
icon_on = "sleep"
icon_off = "no_sleep"

[[block]]
block = "toggle"
format = "  $icon  "
command_state = 'if [ "$($HOME/bin/darkmode status)" = "dark" ]; then echo y; fi'
command_on = "$HOME/bin/darkmode toggle"
command_off = "$HOME/bin/darkmode toggle"

[[block]]
block = "hueshift"
format = " 󱩌 {$temperature} "
click_temp = 4000

[[block]]
block = "backlight"
format = " $icon $brightness.eng(width:1) "
step_width = 1
minimum = 1

[[block]]
block = "sound"
driver = "pulseaudio"
headphones_indicator = true
show_volume_when_muted = true
format = " $icon $volume.eng(width:1) "
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
warning_bg = { link = "idle_bg" }
warning_fg = { link = "idle_fg"}
idle_bg = { link = "info_bg" }
idle_fg = { link = "info_fg"}

[[block]]
block = "battery"
interval = 30
format = " $icon $percentage "
full_format = " $icon $percentage "

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1267:12613:ASUE140C:00_04F3:3145_Keyboard"
format = "  $layout "
[[block.click]]
button = "left"
cmd = "swaymsg input '1267:12613:ASUE140C:00_04F3:3145_Keyboard' xkb_switch_layout next"
[block.mappings]
"French (N/A)" = "fr"
"English (Colemak-DH)" = "colemak-dh"
"English (US)" = "en"

[[block]]
block = "time"
interval = 10
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m/%y %R', l:fr_FR) "
short = " $icon $timestamp.datetime(f:'%R')"
